<?php //namespace modules\mod_instantfblogin/** * @package INSTANTFBLOGIN::modules * @subpackage mod_instantfblogin * @author Joomla! Extensions Store * @copyright (C) 2015 - Joomla! Extensions Store * @license GNU/GPLv2 http://www.gnu.org/licenses/gpl-2.0.html */
defined('_JEXEC') or die;if ($params->get('pretext', null)): ?>
	<div class="jfbl-pretext">
		<p><?php echo $params->get('pretext', null); ?></p>
	</div>
<?php endif;// Retrieve chosen template$ifblTemplate = $params->get('template', '');$ifblGPlusTemplate = $params->get('gplus_template', '');$ifblTwitterTemplate = $params->get('twitter_template', '');$ifblLinkedinTemplate = $params->get('linkedin_template', '');$loginType = $ifblSession->get('socialLoginType');$syncedLogout = null;// Init for multiple modules instances
if(!isset($gplusLoginURL) && $app->get('ifblgp_login_url', false)) {
	$gplusLoginURL = $app->get('ifblgp_login_url');
}

if(!isset($twitterLoginURL) && $app->get('ifbltw_login_url', false)) {
	$twitterLoginURL = $app->get('ifbltw_login_url');
}

if(!isset($linkedinLoginURL) && $app->get('ifbldn_login_url', false)) {
	$linkedinLoginURL = $app->get('ifbldn_login_url');
}// Include Joomla login formif($params->get('login_form_type', 'jfb') == 'jfb') {	$joomlaTmpl = $params->get('joomla_template', '');	require JModuleHelper::getLayoutPath ( 'mod_instantfblogin', $params->get ( 'layout', 'default_' . $joomlaTmpl . 'joomla' ) );}if ($redirectLinkType == 'logout') : 	//Retrieve FB user id	$fbUserID = $ifblSession->get('fbUserID');	// Retrieve FB pic	$picSize = $params->get('fbavatar_size', 'normal');	if($loginType == 'facebook') {		$socialPic='https://graph.facebook.com/'.$fbUserID.'/picture?type='.$picSize;		// Manage synced logout calling FB JS API callback		$syncedLogout = $params->get('facebook_logout', 1) ? 'fblogout(this);return false;' : null;	} elseif($loginType == 'twitter') {		// Manage synced logout calling FB JS API callback		$syncedLogout = null;		$picSize = 'small';		if(!isset($socialPic)) {
			$socialPic = modInstantfbloginHelper::getTwitterPicture($joomlaUserObject->id);
		}	} elseif($loginType == 'google') {		// Manage synced logout calling hidden logout iframe for Google Plus
		$syncedLogout = $params->get('facebook_logout', 1) ? 'gpluslogout(this);return false;' : null;		if(!isset($socialPic)) {
			$socialPic = modInstantfbloginHelper::getGPlusPicture($joomlaUserObject->id);
		}	} elseif($loginType == 'linkedin') {		// Manage synced logout calling FB JS API callback		$syncedLogout = null;		if(!isset($socialPic)) {
			$socialPic = modInstantfbloginHelper::getLinkedinPicture($joomlaUserObject->id);
		}	}	switch ($picSize) {		case 'small':			$imgStyle = 'style="width:50px;"';			break;				case 'normal':			$imgStyle = 'style="width:100px;"';			break;					case 'large':			$imgStyle = 'style="width:180px;"';			break;	}		?>
	<form method="post" id="jfbl-logout-form" onsubmit="<?php echo $syncedLogout;?>">		<?php if(@$socialPic && $params->get('show_fbavatar', 1)):?>			<img <?php echo $imgStyle;?> src="<?php echo $socialPic?>" alt="Profile pic" />		<?php endif;?>		<div class="fbprofile_name">			<?php $nameToFetch = $params->get('usefullname', 'name'); ?>			<a href="<?php echo $moduleLinks['profileLink'];?>">				<?php echo JText::sprintf('COM_INSTANTFBLOGIN_HINAME', htmlspecialchars($joomlaUserObject->get($nameToFetch))); ?> 			</a>		</div>		<div class="logout-button">			<input type="submit" name="Submit" class="btn btn-primary" value="<?php echo JText::_('JLOGOUT'); ?>" />			<input type="hidden" name="option" value="com_users" />			<input type="hidden" name="task" value="user.logout" />			<input type="hidden" name="return" value="<?php echo $return; ?>" />			<?php echo JHtml::_('form.token'); ?>		</div>	</form><?php else : 	// Form and button template	$customText = null;	if($params->get('use_custom_text', 0)) {		$customText = $params->get('custom_text', null);	}		$customGPlusText = null;
	if($params->get('use_custom_gplus_text', 0)) {
		$customGPlusText = $params->get('custom_gplus_text', null);
	}	$customTwitterText = null;	if($params->get('use_custom_twitter_text', 0)) {		$customTwitterText = $params->get('custom_twitter_text', null);	}		$customLinkedinText = null;
	if($params->get('use_custom_linkedin_text', 0)) {
		$customLinkedinText = $params->get('custom_linkedin_text', null);
	}		// Custom loadin message	$customLoadingMsg = $params->get('custom_loading_msg', false);	$customMsg = $params->get('loading_msg', JText::_('COM_INSTANTFBLOGIN_PLEASE_WAIT'));	$displayMsg = $customLoadingMsg ? $customMsg : JText::_('COM_INSTANTFBLOGIN_PLEASE_WAIT');	?>	<form id="jfbl-login-form-fb" >		<?php if($fbLoginActive && $appId && $secret): ?>			<a href="javascript:void(0);" onclick="fblogin();return false;" class="ifbl_fbloginbutton">				<?php if($customText):?>					<label class="jfbl-modlgn <?php echo $ifblTemplate;?>"><?php echo $customText;?></label>				<?php endif;?>				<img alt="Facebook Login" style="border:none" src="<?php echo JURI::base();?>modules/mod_instantfblogin/assets/images/fbk<?php echo $ifblTemplate;?>.png" />			</a>		<?php endif; ?>		<?php if($gplusLoginActive && $gplusClientId && $gplusKey): ?>			<a href="<?php echo $gplusLoginURL;?>" class="ifbl_gplusloginbutton">				<?php if($customGPlusText):?>					<label class="jfbl-modlgn <?php echo $ifblGPlusTemplate;?>"><?php echo $customGPlusText;?></label>				<?php endif;?>				<img alt="Google Login" style="border:none" src="<?php echo JURI::base();?>modules/mod_instantfblogin/assets/images/gplus<?php echo $ifblGPlusTemplate;?>.png" />			</a>		<?php endif; ?>		<?php if($twitterLoginActive && $twitterKey && $twitterSecret): ?>			<a href="<?php echo $twitterLoginURL;?>" class="ifbl_twitterloginbutton">				<?php if($customTwitterText):?>					<label class="jfbl-modlgn <?php echo $ifblTwitterTemplate;?>"><?php echo $customTwitterText;?></label>				<?php endif;?>				<img alt="Twitter Login" style="border:none" src="<?php echo JURI::base();?>modules/mod_instantfblogin/assets/images/twt<?php echo $ifblTwitterTemplate;?>.png" />			</a>		<?php endif; ?>		<?php if($linkedinLoginActive && $linkedinAppid && $linkedinSecret): ?>			<a href="<?php echo $linkedinLoginURL;?>" class="ifbl_linkedinloginbutton">				<?php if($customLinkedinText):?>					<label class="jfbl-modlgn <?php echo $ifblLinkedinTemplate;?>"><?php echo $customLinkedinText;?></label>				<?php endif;?>				<img alt="Linkedin Login" style="border:none" src="<?php echo JURI::base();?>modules/mod_instantfblogin/assets/images/lkin<?php echo $ifblLinkedinTemplate;?>.png" />			</a>			<?php if(version_compare(PHP_VERSION, '5.4', '<')): ?>				<label class="jfbl-modlgn"><?php echo JText::_('COM_INSTANTFBLOGIN_LINKEDIN_REQUIRES_PHP54');?></label>			<?php endif;?>		<?php endif;?>		<?php if($params->get('facebook_show_loading', 1)):?>			<div id="facebook-login" style="display:none; text-align:center">				<img style="border:none" alt="loading" src="<?php echo JURI::base();?>modules/mod_instantfblogin/assets/images/loading.gif" />				<div class="ifbl_custom_msg"><?php echo $displayMsg;?></div>			</div>		<?php endif;?>	</form><?php endif;if ($params->get('posttext', null)): ?>	<div class="jfbl-posttext">		<p><?php echo $params->get('posttext', null); ?></p>	</div><?php endif; ?>